### ISSUE TITLE
Allow spawning particle systems with an initial disabled state

### ISSUE THREAD

**Issue by rparrett** [mbrea-c/bevy_firework#10]
I have a particle effect that I would like to turn on/off without removing any live particles.

I don't want the particle system to be active immediately though. I currently find myself having to write a system to disable a particular `ParticleSpawnerData` immediately after `bevy_firework` adds it.

**Comment by mbrea-c** [comment]
Good point, I can add a `starts_disabled` field to `ParticleSpawnerSettings` to configure this. Should be a straightforward change, I'll try to make a PR after I'm done with work.
