### ISSUE TITLE
Plans for Bevy 0.14?

### ISSUE THREAD

**Issue by masonk** [mbrea-c/bevy_firework#17]
I'd like to play around with bevy_firework, but I'm already upgraded to 0.14.0. I tried to fork and upgrade bevy_firework to 0.14, but it wasn't simple due to the xpbd integration. I'm wondering whether you intend to keep working on this package, e.g., following xpbd to Avian and bumping Bevy to 0.14.

If so, I can try to put together a mergeable upgrade patch. Otherwise, I should look elsewhere for particles :). I do you think your examples look better than Hanabi, FWIW.

**Comment by mbrea-c** [comment]
I'm actively working on it, but I was running into some rendering bug yesterday that I couldn't figure out. I'll get back to it this afternoon, and make a public branch with the WIP code.

As for the bevy_xpbd update, my plan is to first update to bevy_xpbd 0.5 with the initial 0.14 migration, and then quickly follow-up with an update to Avian. The dependency on xpbd is pretty superficial though, so migrating to Avian shouldn't take more than an afternoon after I get this rendering bug fixed :)

**Comment by mbrea-c** [comment]
#18 sorts out the migration to Bevy 0.14 and bevy_xpbd 0.5. The `bevy_xpbd -> Avian` update should be finished tomorrow if all goes well

**Comment by mbrea-c** [comment]
With #22 the migration to Avian is finished

**Comment by masonk** [comment]
Can’t wait to play with it! I’ll probably rip out Rapier and go to Avian to try the physics too
